//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::books::Entity as Books;
pub use super::lendings::Entity as Lendings;
pub use super::lendings_detail::Entity as LendingsDetail;
pub use super::publishers::Entity as Publishers;
pub use super::readers::Entity as Readers;
pub use super::staff::Entity as Staff;
