//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "staff")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub login: String,
    pub password: String,
    pub phone_number: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::lendings::Entity")]
    Lendings,
}

impl Related<super::lendings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lendings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
